### ISSUE TITLE
Tiling issue with asset id: 10718

### ISSUE THREAD

**Issue by firstgle** [AnalyticalGraphicsInc/cesium-ion-community#59] opened 2018-11-22 08:39 UTC
I uploaded an terrain geotiff file to cesium ion, during tiling process, I got an error message: We're having trouble with your data. To help fix it, please open an issue in our Github repository.

**Comment by hpinkos** [comment] 2018-11-26 15:27
Thanks @firstgle, our tiling team will investigate to see what the problem is and give you an update soon.

**Comment by OmarShehata** [comment] 2020-08-06 21:55
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

This may have been fixed now. Since the asset has been deleted we can't re-test it. Give it a try, and if you have any follow up questions, please post on the community forum!

**Closed as completed by OmarShehata** 2020-08-06 21:55 UTC
