### ISSUE TITLE
Not Found ArcGisMapServerImagery Tiles

### ISSUE THREAD

**Issue by HiDavidWong** [AnalyticalGraphicsInc/cesium-ion-community#219] opened 2019-08-30 08:55 UTC
I published a WMTS Service by ArcGIS Server, then I used Cesium.ArcGisMapServerImageryProvider to load this service, but occur many errors: 
![image](https://user-images.githubusercontent.com/54704484/64006884-c16f7580-cb45-11e9-8efa-fbd550d69061.png)
Not some tiles not found, but all tiles not found. But I used ArcGIS for JavaScript API can normally load all tiles.
Please help me solve this problem!

**Comment by OmarShehata** [comment] 2019-08-30 16:21
Can you share the code you're using to add this imagery layer to CesiumJS? Are you able to reproduce the issue in Sandcastle (https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html) ? 

If so, can you share a link to an example I can run? (You can press "Share" at the top and paste the link you get here).

**Comment by HiDavidWong** [comment] 2019-09-01 02:48
https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html#c=zVVba9swFP4rwi9NIZV8je0s7da6UAoNuyRbXwxDsZREqyxlsnJxQ/775NjN4o4x1odSg42OztGn73znSF5hBVaMrqkC50DQNUhowZY5/Laf65xkezORQmMmqDo5fZeKVCAEpo7v2j3iEpr5PnHD2At6vu9Gk8jx7SikG8AKgIGWD1R0AdOVucKcETCVCkjBS/OhgOCyAlwZGgslV4xQddlmck8nQ7wYM05HVK1YRm9zPKOq/NSEd7apAOZZKt4HqTXXetFHaL1eQ8JmTGOe/YSZzJFmWBCml+hho2YS/ZM/uh+OR+9Tq1vDc1xSVW2QfDZ0vt8Obw6uQpecVi5Cp3jJ9cFhMs2xrjys4ox+LGYLMTu4tclpiLVimxHVt9dHCLYb5XlqpWJX630sz9UbkgdVKSAH2tBGB13QdlQJskPb8XGCLbsxvsh1M0ok3709rZO21l8VH9N8wbF+NZX3Am8fjUqleTe7vxC9bhO9VNkNK4x2VU9Q9Upkj7iZC+Iel+DSsNxfJJDVFO6qyhYQE/Kc0+H0twCuqtH/Qly1IJKXQCQtiOuXQFw3VaqXFRkVFGY4pwrDKS/H8qkKZKmwZlL0gdf0KqGFZqKZPKpqgpU2Iyy8zpkTxD3biaEbRLYfx4EbdUFgChI5IQzsOIzjyPO6wHMC2/VdGPpuHLtu5J82e0jFqLnT6z0aJgDMKSZMzPqgB93Ic6LAs0MnjIOo+xSxYDqb98GZA4PQdjzPdcOg58U9/3eIktz0lV2bu31LWF1rsD+5F/XsB5YvpNJVB3YgRLo5VAWaLLMHqmFWFJV6A/S0aEDYCjBynlrPfkipBTKOi8J4pkvOR+yRptbFAJn41jIu95l9NKfB3C5VyNy5uKsnIYQDZMw/V2kp+QSrI8Rf

**Comment by OmarShehata** [comment] 2019-09-01 12:35
Thanks for the code example @HiDavidWong. It looks like the issue here with the providerD (the `ArcGisMapServerImageryProvider`) is (1) that it's attempting to load it over http, but the Sandcastle app is running on https, so the browser blocks the [mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content).

Trying it locally to get around that, the error is:

```
An error occurred in "ArcGisMapServerImageryProvider": Tile spatial reference WKID 4490 is not supported.
```

It looks like only 102100, 102113, and 4326 are currently supported, according to:

https://github.com/AnalyticalGraphicsInc/cesium/blob/e0e010a32e988ca8f6d9b948c51ee1c50fb25554/Source/Scene/ArcGisMapServerImageryProvider.js#L172-L175 

You may need to reproject your imagery to get this example to work.

Note that this looks different from the errors in your initial post. The unsupported WKID should be caught at the beginning and only produce one error. Is the imagery in the code example above served by ArcGIS Server in the same way?

**Comment by HiDavidWong** [comment] 2019-09-01 13:08
Thank you for your reply. In my example, all four of providers(A-D) used to load the same imagery. When I use providers(A-C) to load the imagery, occur so many errors( all tiles not fount ). But when I use providerD, an error occurred, WKID 4490 is not  supported. Now, I wonder if the provider(A-C) can't find tiles because the ArcGisMapServerImageryProvider doesn't support 4490?

**Comment by OmarShehata** [comment] 2019-09-01 16:06
Ah, I didn't realize the problem was also in the other providers. Running them locally reveals a CORS error:

```
Access to image at 'http://www.digitalcq.com/....' from origin 'http://localhost:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

So it looks like you may need to configure the server to allow requests from other origins (in addition to the http/https issue).

**Comment by OmarShehata** [comment] 2019-10-04 14:12
I'm closing this but feel free to follow up if you're still having issues @HiDavidWong here or on the Cesium forum (https://groups.google.com/forum/#!forum/cesium-dev).

**Closed as completed by OmarShehata** 2019-10-04 14:12 UTC
