### ISSUE TITLE
Tiling issue with asset id: 13841

### ISSUE THREAD

**Issue by swtgeo** [AnalyticalGraphicsInc/cesium-ion-community#93] opened 2019-01-13 13:19 UTC
<Please provide a short summary of your data.> These are OSGB datas ,i use cesium ion upload these datas,but failed

**Comment by lilleyse** [comment] 2019-01-14 13:57
Closing as duplicate of https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/92.

**Closed as completed by lilleyse** 2019-01-14 13:57 UTC
