### ISSUE TITLE
502 Bad gateway response OAuth Token Exchange

### ISSUE THREAD

**Issue by pipan** [AnalyticalGraphicsInc/cesium-ion-community#270] opened 2020-01-21 11:27 UTC
I am trying to implement Cesium OAuth in my application. I am implementing it by following this doc https://cesium.com/docs/oauth/ but I am stuck at step Token Exchange.

Everytime I send a POST request to this URL https://api.cesium.com/oauth/token I receive this response(status: 502):

```html
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.1</center>
</body>
</html>
```

If my POST data are incorrect I would expect some other http response and other response code. So I am not sure if there is a problem on my side or on your side. If I send a GET request to this URL https://api.cesium.com/oauth/token I receive correct response (status: 405):

```json
{
  "code": "MethodNotAllowed",
  "message": "GET is not allowed"
}
```

Any help would be appreciated

**Comment by OmarShehata** [comment] 2020-01-21 22:45
Thanks for reporting this @pipan . I'm able to reproduce. Looks like the issue is that the first time you make the POST request to get the token, using the given `code` you got from the OAuth screen. That request will succeed, and you'll get the token. Calling the same request again will produce this bad gateway error. 

@pipan can you confirm you're seeing this behavior? Here's the curl script I'm using to verify this:

```
curl -X POST \
  https://api.cesium.com/oauth/token \
  -F grant_type=authorization_code \
  -F client_id=ID_FOR_YOUR_APP \
  -F code=CODE_FROM_OAUTH_REDIRECT \
  -F redirect_uri=https://google.com/
```

@mramato is this expected behavior?

**Comment by mramato** [comment] 2020-01-22 01:39
The code is one time use, so that's expected behavior, but we should be returning an `Invalid authorization code` in that case, not a 502.  Taking a quick look at the code, I see why this is happening and we can get it fixed soon.

**Comment by pipan** [comment] 2020-01-22 09:47
Thank you for your reply. I checked if I use the same code twice, but I always use new code. @OmarShehata your CURL example gave me an idea to get rid of code_challenge and code_challenge_method (PKCE Extension) to simplify my problem and it worked. I received successfull response. So my problem was in generating code_challenge. I scrolled to the bottom of this tutorial https://cesium.com/docs/oauth/ and found en example of generating code_challenge. I forgot to replace some characters (+,/,=) in my code. Everything works as expected. 

When I got success response I tried to send request with the same code and then I got 502 Bad gateway response. So it seems that 502 response is send for invalid code and invalid code_challenge.

My issue is solved, so I think you can close this ticket. Thank you again for your help.

**Comment by mramato** [comment] 2020-01-22 13:02
Thanks for following up @pipan I'll close this since the issue is fixed on your end. I wrote up a separate issue for us to fix the unexpected 502 for invalid codes.

**Closed as completed by mramato** 2020-01-22 13:02 UTC
