### ISSUE TITLE
Styling issue with CityGML - asset ID: 91128

### ISSUE THREAD

**Issue by buyukdemircioglu** [AnalyticalGraphicsInc/cesium-ion-community#307] opened 2020-04-15 20:50 UTC
Hello. I tried Cesium Stories styling features on my CityGML dataset, but it looks like only auto generated attributes by Cesium Ion's 3DTiles converter can be used for styling (Height, Latitute, Logitude and TerrainHeight). Other attributes of the uploaded dataset cannot be used for styling somehow. 

Thanks

**Comment by OmarShehata** [comment] 2020-04-16 13:49
This appears to be a bug, since you can see that the properties are indeed there if you click on any building. Will update this issue once we find out the cause.

**Comment by OmarShehata** [comment] 2020-04-21 13:00
@buyukdemircioglu the issue here was specifically with feature properties with spaces in their names. We've just pushed a fix for this, so you should be able to style all those properties now! Full changelog here: https://cesium.com/ion/changelog#2020-04-20

**Closed as completed by OmarShehata** 2020-04-21 13:00 UTC
