### ISSUE TITLE
Tiling issue with asset id: 60451

### ISSUE THREAD

**Issue by dagursal** [AnalyticalGraphicsInc/cesium-ion-community#255] opened 2019-12-10 16:06 UTC
Hi,
I have tile set of a place which asset id is 60451. when update the data i got this error:

Error: File Not Found
File: Scene/Cesium.json

Is there any problem ? Can you help me?

**Comment by OmarShehata** [comment] 2019-12-10 21:27
The problem is that your tileset JSON file is inside a subfolder. You entered `Cesium.json` as the JSON file, when it should be `Scene/Cesium.json`.

Let me know if that solves the issue.

**Comment by OmarShehata** [comment] 2019-12-17 15:18
@dagursal closing this since that should resolve the problem, but feel free to follow up if you're still having issues.

**Closed as completed by OmarShehata** 2019-12-17 15:18 UTC
