### ISSUE TITLE
Cesium visualization issue with asset id: 11154

### ISSUE THREAD

**Issue by samuel-dotman** [AnalyticalGraphicsInc/cesium-ion-community#76] opened 2018-12-17 10:51 UTC
An error occurred while rendering.  Rendering has stopped.
undefined
DeveloperError: Expected width to be greater than 0, actual value was 0
Error
    at new DeveloperError (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:524:19)
    at Function.Check.typeOf.number.greaterThan (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:1838:19)
    at new Texture (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:84898:29)
    at createTextures (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:211062:36)
    at updateFramebuffers (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:211120:13)
    at GlobeDepth.update (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:211194:9)
    at updateAndClearFramebuffers (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:234136:29)
    at executeCommandsInViewport (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:233950:17)
    at updateAndExecuteCommands (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:233751:13)
    at render (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:234376:9)
Uncaught DeveloperError: drawingBufferWidth must be greater than zero.
Error
    at new DeveloperError (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:524:19)
    at PerspectiveOffCenterFrustum.getPixelDimensions (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:57719:19)
    at PerspectiveFrustum.getPixelDimensions (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:58125:39)
    at getPickPerspectiveCullingVolume (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:234549:33)
    at getPickCullingVolume (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:234570:16)
    at Scene.pick (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:234631:36)
    at pickEntity (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:250784:35)
    at pickAndSelectObject (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:251423:35)
    at handleMouseUp (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:74884:21)
    at handlePointerUp (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:75284:13) (on line 57719 of https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js)
Uncaught DeveloperError: drawingBufferWidth must be greater than zero.
Error
    at new DeveloperError (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:524:19)
    at PerspectiveOffCenterFrustum.getPixelDimensions (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:57719:19)
    at PerspectiveFrustum.getPixelDimensions (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:58125:39)
    at getPickPerspectiveCullingVolume (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:234549:33)
    at getPickCullingVolume (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:234570:16)
    at Scene.pick (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:234631:36)
    at pickEntity (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:250784:35)
    at pickAndSelectObject (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:251423:35)
    at handleMouseUp (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:74884:21)
    at handlePointerUp (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:75284:13) (on line 57719 of https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js)
Uncaught DeveloperError: drawingBufferWidth must be greater than zero.
Error
    at new DeveloperError (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:524:19)
    at PerspectiveOffCenterFrustum.getPixelDimensions (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:57719:19)
    at PerspectiveFrustum.getPixelDimensions (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:58125:39)
    at getPickPerspectiveCullingVolume (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:234549:33)
    at getPickCullingVolume (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:234570:16)
    at Scene.pick (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:234631:36)
    at pickEntity (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:250784:35)
    at pickAndSelectObject (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:251423:35)
    at handleMouseUp (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:74884:21)
    at handlePointerUp (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:75284:13) (on line 57719 of https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js)
Uncaught DeveloperError: drawingBufferWidth must be greater than zero.
Error
    at new DeveloperError (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:524:19)
    at PerspectiveOffCenterFrustum.getPixelDimensions (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:57719:19)
    at PerspectiveFrustum.getPixelDimensions (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:58125:39)
    at getPickPerspectiveCullingVolume (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:234549:33)
    at getPickCullingVolume (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:234570:16)
    at Scene.pick (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:234631:36)
    at pickEntity (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:250784:35)
    at pickAndSelectObject (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:251423:35)
    at handleMouseUp (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:74884:21)
    at handlePointerUp (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:75284:13) (on line 57719 of https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js)

**Comment by lilleyse** [comment] 2018-12-17 14:44
Hi @samuel-dotman, that error looks like WebGL crashed or failed to initialize. I confirmed that the tileset loads in Cesium for me.

Are you able to run other Cesium apps? It's possible the tileset is using more GPU memory than your system has available.

**Comment by lilleyse** [comment] 2019-03-29 23:05
@samuel-dotman, I'm going to close this but let us know if you continue to run into this problem.

**Closed as completed by lilleyse** 2019-03-29 23:05 UTC

**Comment by samuel-dotman** [comment] 2020-11-18 00:41
Thank you for your reply.
I'm so late to check the issue.
It is not yet clear to me.
Sometimes this problem happens.

**Comment by wuming2019** [comment] 2022-04-13 10:04
So how do you solve this problem

An error occurred while rendering. Rendering has stopped.
DeveloperError: drawingBufferWidth must be greater than zero.

Error
    at new DeveloperError (webpack-internal:///./node_modules/cesium/Source/Core/DeveloperError.js:41:11)
    at PerspectiveOffCenterFrustum.getPixelDimensions (webpack-internal:///./node_modules/cesium/Source/Core/PerspectiveOffCenterFrustum.js:394:11)
    at PerspectiveFrustum.getPixelDimensions (webpack-internal:///./node_modules/cesium/Source/Core/PerspectiveFrustum.js:346:33)
    at Camera.getPixelSize (webpack-internal:///./node_modules/cesium/Source/Scene/Camera.js:3046:32)
    at updateBoundingVolume (webpack-internal:///./node_modules/cesium/Source/Scene/BillboardCollection.js:1805:36)
    at BillboardCollection.update (webpack-internal:///./node_modules/cesium/Source/Scene/BillboardCollection.js:2090:3)
    at EntityCluster.update (webpack-internal:///./node_modules/cesium/Source/DataSources/EntityCluster.js:931:31)
    at PrimitiveCollection.update (webpack-internal:///./node_modules/cesium/Source/Scene/PrimitiveCollection.js:383:19)
    at PrimitiveCollection.update (webpack-internal:///./node_modules/cesium/Source/Scene/PrimitiveCollection.js:383:19)
    at PrimitiveCollection.update (webpack-internal:///./node_modules/cesium/Source/Scene/PrimitiveCollection.js:383:19)

**Comment by apgk** [comment] 2022-04-14 12:02
> 
Invalid configuration

maximumScreenSpaceError : 32 or 64,

skipLevelOfDetail : true,

immediatelyLoadDesiredLevelOfDetail : true

**Comment by shehzan10** [comment] 2022-04-19 03:47
Hi @wuming2019 @apgk - The [Community Forum](https://community.cesium.com) would be a more suitable place for your questions. The community and Cesium's engineers will be able to help out.
