### ISSUE TITLE
Can the front-end project based on cesiumJS be fully localized？

### ISSUE THREAD

**Issue by traworduu** [AnalyticalGraphicsInc/cesium-ion-community#241] opened 2019-11-10 08:49 UTC
I want to develop a 3-D earth satellite project through cesiumJS. I know that token is necessary to display a 3-D earth, but can I display a earth locally? Moreover, whether the follow-up development can be fully localized, such as simulating the movement of satellites？

**Comment by OmarShehata** [comment] 2019-11-11 02:33
Duplicate of https://github.com/AnalyticalGraphicsInc/cesium/issues/8380#issuecomment-552267508.

**Closed as completed by OmarShehata** 2019-11-11 02:33 UTC
