### ISSUE TITLE
Tiling issue with asset id: 28974

### ISSUE THREAD

**Issue by Brynyard** [AnalyticalGraphicsInc/cesium-ion-community#174] opened 2019-05-25 18:13 UTC
<Please provide a short summary of your data.>

**Comment by Brynyard** [comment] 2019-05-27 08:18
Reuploaded as 29071

**Comment by OmarShehata** [comment] 2019-05-30 02:28
I think this is a known issue with glTF models greater than 500 mb. Is there any way you're able to split it into 2 or more pieces in the meantime?

**Comment by Brynyard** [comment] 2019-05-30 18:11
I've already slashed it significantly down from 14 GB, and even that is just a portion of a small dataset. And this was just a test to see if Ion is a viable solution, and if it can't even slice more than 500 MB, then the answer to that question would be "no". I've also tried .obj and .dae with various other errors (obj can't handle that many files, and dae can't have id's above 1000).

**Comment by OmarShehata** [comment] 2019-06-03 20:01
Just to clarify, I have been able to tile models that are ~20 GB on ion (in those cases they were split into several OBJ or DAE files smaller around 50 to 200 mb each) so it should be able to handle the full 14 GB model if formatted that way.

The issue with handling individual files that are larger is an open bug that we're actively working on fixing, and I'll update this issue once a fix is deployed. 

In the mean time, can you tell me a bit about how you're authoring these models? Is it exported directly from a photogrammetry software? I'm also curious about:

> obj can't handle that many files

Was this an error you got from ion?

**Comment by Brynyard** [comment] 2019-06-03 20:16
If you upload an a .zip with an obj with many textures (in my case ~72000), the magic that is supposed to give you a choice about what to do with the file  usually didn't happen (absolutely no indication about anything happening or not, is this supposed to stay like this?), but when it occasionally did (after about 15-20 minutes) it never seemed to recognize the .obj file and thought is was just a bunch of ortho images. The same issue with .dae, but it eventually recognized it and gave me the option to slice it, but failed complaining about duplicate textures on id's 1000+ (which isn't the case).

If I where to test with many files, how should I organize them, how to join them into a single 3D tiles dataset, and how can one manage many files in a reasonable manner (as this would lead to even more files)?

**Comment by OmarShehata** [comment] 2019-06-12 21:04
> the magic that is supposed to give you a choice about what to do with the file usually didn't happen (absolutely no indication about anything happening or not, is this supposed to stay like this?)

This is indeed a bug. The issue is that zip files that have more than 60k files, or more than 4 GB use the Zip64 format, which needs to be handled slightly differently. We're working on a fix for this and hopefully should have something deployed for that sometime next week. 

In general, if you upload a couple hundred OBJ or glTF models with textures all together, you'll get one 3D Tileset. As long as the individual models are positioned relative to each other, the final produced tileset will represent the full model, no need to worry about manually joining or anything. The solution to handling this many files in a reasonable manner would be to zip it, but this won't work until the zip64 fix is deployed.

I can update this issue as soon as that fix is deployed.

**Comment by OmarShehata** [comment] 2019-06-28 18:33
Just an update here, the zip64 upload issue has been fixed, so you should be able to upload any amount of files by zipping and uploading that.

If you encounter tiling errors after upload, let me know the new asset ID and I'll take a look. I appreciate your feedback and patience here.

**Comment by OmarShehata** [comment] 2020-08-06 21:35
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!

**Closed as completed by OmarShehata** 2020-08-06 21:35 UTC
