### ISSUE TITLE
Cesium visualization issue with asset id: 45599

### ISSUE THREAD

**Issue by dmbagh** [AnalyticalGraphicsInc/cesium-ion-community#229] opened 2019-09-30 17:23 UTC
A set of simple textured buildings, colored extrusions, and more complicated meshes representing guard and water towers. There is also a textured fence around the camp. A smaller dataset (barracks only) works well.

**Comment by OmarShehata** [comment] 2019-09-30 19:31
Hey @dmbagh ! Thanks for reporting this.

Is the issue that the colors aren't showing up? Or other things as well? I can see the textured buildings seem to appear correctly, but that the fence seems to sink into the ground.

**Comment by dmbagh** [comment] 2019-09-30 19:32
Hi Omar,

it crashes all the time just after a few seconds :(

Dmitri
––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

Dmitri Bagh | Scenario Creation Analyst

Safe Software Inc.

Suite 1200 - 9639 137A Street, Surrey, BC Canada V3T 0M1
T 604.501.9985 x 276
dmitri.bagh@safe.com | www.safe.com

––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

<http://www.safe.com/emailsignature>

**Comment by OmarShehata** [comment] 2019-09-30 20:41
@dmbagh does this crash occur when testing/viewing it in the Cesium ion dashboard, or in [Sandcastle](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html), or only in your app? Are you able to share a link that reproduces this crash? You can email it to support@cesium.com if you prefer not to share it publicly.

**Comment by OmarShehata** [comment] 2019-10-04 14:12
Closing since the crash doesn't seem to occur when tiling with Cesium ion.

**Closed as completed by OmarShehata** 2019-10-04 14:12 UTC
