### ISSUE TITLE
3D model or 3D capture?

### ISSUE THREAD

**Issue by hardreddata** [AnalyticalGraphicsInc/cesium-ion-community#310] opened 2020-04-19 22:50 UTC
All,

Can I please get some advice on the difference between these tiling choices in Cesium Ion. I have been lazily clicking through processing and didn't notice the two distinct choices. 

I did look in the help which includes the (deprecated) Photogrammetry or BIM/CAD options per

![image](https://user-images.githubusercontent.com/42530666/79701825-8774fe80-82e3-11ea-8eab-815d9b65674d.png)

It seems the 3D capture performs best for drone data sets. As a spin-off I don't think I can inspect a previously tiled asset to see what choice I made?

Many thanks.

**Comment by mramato** [comment] 2020-04-21 13:22
Thanks for writing up this issue, @RussellGrew, we will fix the doc so that it is up-to-date with the official options.

3D Capture - As you suspected, this is meant for drone, lidar, or any mesh data that has been captured or generated via real world sensors.

3D Model is meant for "constructed" 3D models, the kind you would build with a modeling tool, such as Blender, Revit, Microstation, etc.. 

Long term, we want to eliminate the need for the user to make this choice at all and detect the best algorithm to use based on the content of the uploaded model.

I believe we have an issue for allowing a user to see their previous choice, but I'll have to find it. I agree it would be useful. We'll leave this open either way until the issue is linked and the doc issue is fixed.

Thanks again!

**Comment by OmarShehata** [comment] 2020-05-20 17:20
Note that at the time of writing, one difference to be aware of is that "3D Capture" models are not affected by lighting (like based on the time of day in CesiumJS), since the lighting for most photogrammetry models is baked into the textures.

**Comment by OmarShehata** [comment] 2020-08-06 16:39
We're closing down the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

This issue has been moved here: https://community.cesium.com/t/3d-model-or-3d-capture/10465.

**Closed as completed by OmarShehata** 2020-08-06 16:39 UTC
