### ISSUE TITLE
Invalid Parameter: 'options.position[0]' must be a longitude value between -180.0 and 180.0."

### ISSUE THREAD

**Issue by KonWoj** [AnalyticalGraphicsInc/cesium-ion-community#285] opened 2020-02-16 22:02 UTC
Hi,
I ran into a weird problem. When I was trying to create a new asset, placed in a correct location (options.position  = [21.02289318, 52.08170731,143.40148655931674]) via rest api, I keep getting the error as in the title of this issue. Is it a bug? Or am I doing something wrong?

**Comment by OmarShehata** [comment] 2020-02-18 13:08
Hey @KonWoj , I'm not able to reproduce this error with the provided coordinates. Are you still seeing this error? If so, can you share more details about how you're calling the REST API? Or if you're calling with a Python/NodeJS script, sharing that script so we can reproduce with it?

**Comment by KonWoj** [comment] 2020-02-18 18:37
Hey, yes, the error still occurs. That's piece of Javascript code I use for uploading the asset https://jsfiddle.net/65sbxd8w/

**Comment by OmarShehata** [comment] 2020-02-18 19:14
This is odd. Calling that same code with my token produces a successful response.

When you check the network tab in your browser, and filter for requests to `https://api.cesium.com/v1/assets` do you see the following Form Data sent in the request?

![image](https://user-images.githubusercontent.com/1711126/74769720-e6bd8080-5258-11ea-81a6-406c9fdee67e.png)

**Comment by OmarShehata** [comment] 2020-03-05 20:03
Closing since we're unable to reproduce this. @KonWoj if you're still running into that issue, can you share the form data you see in your network tab? That'll us figure out if it's an issue in the request, or on our side.

**Closed as completed by OmarShehata** 2020-03-05 20:03 UTC
