### ISSUE TITLE
Hang while tiling terrain

### ISSUE THREAD

**Issue by kring** [AnalyticalGraphicsInc/cesium-ion-community#256] opened 2019-12-10 23:30 UTC
I uploaded a ZIP file containing two large .ASC(+.PRJ) files, but Ion has been stuck at 27% progress since yesterday. My next move is to upload them individually or from S3, but it'd be good to know what's wrong with the ZIP approach. Here's my asset:
https://cesium.com/ion/assets/60278

**Comment by kring** [comment] 2019-12-11 02:28
I'm not having any luck uploading this data from S3, either, even when I reduce it down to just a single terrain file. See this asset ID:
https://cesium.com/ion/assets/60557

In this case it doesn't hang, though. It just fails immediately with a generic error.

**Comment by kring** [comment] 2019-12-11 03:13
Aand I tried upload the files just normally, too, and it's still no good:
https://cesium.com/ion/assets/60558

gdalinfo is happy enough with this terrain, and the projection is nothing too crazy, so I'm not sure what might be wrong.

**Comment by OmarShehata** [comment] 2019-12-11 13:58
It is possible that tiling this asset takes longer than usual, and ion jobs currently have a 24 hour timeout, so that might be why the first one is failing. I'll see if I can confirm if this is the case.

For 60557, that S3 job seems to be failing because ion doesn't have access using the given credentials, which is unusual that it wasn't caught before the job started. Can you verify that the credentials you supplied have list access as well as download access?

60558 seems to be an error on our end, the job isn't starting there. 

I think the best avenue here is trying to get the ZIPPed asset to succeed. I'll do some debugging on our end to see if it's just a matter of time for it to tile or if there's something else going on.

**Comment by kring** [comment] 2019-12-11 20:55
~It looks like the ZIP job has ended with an error at this point.~ I re-read what you wrote, and that makes sense. Thanks for looking into it.

You're right about the S3 job, I had the bucket policy wrong. I've fixed that and kicked it off again. 🤞 
https://cesium.com/ion/assets/60862

I was surprised the direct upload failed, that seemed like a very straightforward case. What's going on with that one? Should I just try again maybe?

**Comment by kring** [comment] 2019-12-12 04:46
I tried using GDAL to convert my two terrain files to compressed TIFs. That worked well for the smaller 5m one - Ion was able to tile it just fine. Sorry, no asset ID for that as I've now deleted it. But tiling failed again when I tried to combine the 5m and the 1m files:
https://cesium.com/ion/assets/60902

The only thing unusual about the 1m data is that I had to create the TIFF with the `BIGTIFF=yes` option.

By the way, does Ion automatically choose the higher resolution file to put on "top"? Or does the order in which I add them matter? In believe in STK Terrain Server the user ordered them explicitly.

**Comment by OmarShehata** [comment] 2019-12-12 17:03
> By the way, does Ion automatically choose the higher resolution file to put on "top"? Or does the order in which I add them matter? In believe in STK Terrain Server the user ordered them explicitly.

It does use a fixed ordering (most likely alphabetical) which means it likely won't produce the correct result. The only way to ensure this tiles correctly on ion right now would be to create the 5m asset first on ion, then upload the 1m one with the 5m as the base layer. I opened an issue here to improve this workflow: https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/259

I do believe the issue here is that this tiling job takes more than 24 hours, which exceeds the allowed timeout on ion. We're looking into either increasing the timeout or improving the tiler's speed on these jobs. In the meantime I'm running this tiling job locally and I'll confirm when it completes successfully.

**Comment by kring** [comment] 2019-12-12 20:51
> It does use a fixed ordering (most likely alphabetical) which means it likely won't produce the correct result.

Gotcha. If that were documented I could get the right results by renaming my files.

> I do believe the issue here is that this tiling job takes more than 24 hours

That could have been the cause of the ZIP failure, but the two TIFFs job (https://cesium.com/ion/assets/60902) failed after much less than 24 hours.

I've re-uploaded the 5m job (https://cesium.com/ion/assets/60915), and I'll try layering the 1m on top of it as a separate job today.

By the way, I believe this 1m and 5m data of New South Wales, Australia, is open data. So I'd be happy to see it incorporated into Cesium World Terrain if you guys are up for it. :)

Thanks for your help, Omar!

**Comment by kring** [comment] 2019-12-16 00:02
So the 1m terrain layered on top of the 5m didn't work either. :(
https://cesium.com/ion/assets/61202

**Comment by OmarShehata** [comment] 2019-12-17 15:13
Looks like that last job didn't finish tiling. I was able to tile the two pieces together locally but it produced an invalid terrain tileset (the globe would disappear as you zoomed to the part where the terrain was), so my guess is there might be an issue with the 1m dataset. We're going to investigate this now and I'll update this issue once we have a solution or a workaround.

**Comment by AnaBelgun** [comment] 2020-01-14 22:34
Hi @OmarShehata. Would you please let us know if there's any news with this investigation? we have an important digital twin platform launch in Feb and if this turns out to be an issue with the 1m DEM we need to let the custodian know as soon as we can; if it's a different problem we need to either wait for the ION bug to be fixed or find a different solution if that can't be done in time. Thank you heaps.

**Comment by OmarShehata** [comment] 2020-01-16 15:27
Hey @AnaBelgun, we don't have a solution at this time, but have you tried tiling just the 1m piece, on its own, without using a base layer? My best guess is that there is a data issue here, and that would confirm one way or the other.

**Comment by kring** [comment] 2020-01-16 15:37
Yes I did try that while I was at D61, @OmarShehata. No luck. It's https://cesium.com/ion/assets/61202.

**Comment by OmarShehata** [comment] 2020-01-20 15:36
@kring that asset (61202) is the 1m piece tiled with the 5m as a base layer (which has Cesium World Terrain as base layer). 

I was able to successfully tile and combine the 1m piece with the 5m piece, locally and without Cesium World Terrain. If this would be an acceptable temporary solution I can upload this asset manually into your account. I would also expect tiling the 1m piece on top of the 5m to work without CWT in your ion account (I would recommend using the TIFF version over the ASC since it will tile much faster).

We're now looking into why it's failing on Cesium ion, and if the issue only arises when combining with Cesium World Terrain or not.

**Comment by kring** [comment] 2020-01-20 21:00
Thanks @OmarShehata! Yeah getting that dataset up on ion even without the CWT base would be useful for sure! @AnaBelgun that means that there won't be any terrain outside of NSW, but at least the NSW terrain will be correct.

**Comment by OmarShehata** [comment] 2020-01-22 19:32
@AnaBelgun I've uploaded this dataset to your account as a temporary solution until we can resolve the tiling issue on Cesium ion. You'll find the 1m + 5m merged piece in your account now. Feel free to follow up with any issues there via support@cesium.com since you have access to email support as a commercial account.

**Comment by AnaBelgun** [comment] 2020-01-28 05:25
Awesome! thank you @OmarShehata @kring so much; no idea how useful this is.

**Comment by OmarShehata** [comment] 2020-08-06 21:20
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

I believe the original issue here has been resolved with tiling that particular asset, but for any follow up questions please post on the community forum!

**Closed as completed by OmarShehata** 2020-08-06 21:20 UTC
