### ISSUE TITLE
Tiling issue with asset id: 14481

### ISSUE THREAD

**Issue by glw** [AnalyticalGraphicsInc/cesium-ion-community#98] opened 2019-01-23 19:43 UTC
Hi I've uploaded a sample of las data Im working with. For some reason after importing my data the las file is floating above the ground. I suspected that that the conversion to 3D tiles was not converting the points to what Cesium required. With the reprojected data Im getting an error when uploading. Do las files need to be height above ground in meters?

**Comment by lilleyse** [comment] 2019-01-24 14:51
Hi @glw,

I can confirm it's failing in the projection stage. We're looking into it.

The unprojected data converts fine, but as you noted it's not positioned correctly. It's best to wait until there's a fix for the projected data. I'll update this issue as we get closer.

**Comment by glw** [comment] 2019-01-28 22:17
Ok, thanks for the update!

**Comment by lilleyse** [comment] 2019-06-05 13:21
@glw this was fixed in the latest release. The file converts now but there seems to be issues with the data. Most of the points have the same longitude/latitude values with different heights so when rendered it looks like a straight line.

You can also confirm this by loading the file in http://lidarview.com/

I'm going to close this issue since the tiler problem has been fixed. But I suggest you verify that the data is correct.

**Closed as completed by lilleyse** 2019-06-05 13:21 UTC
