### ISSUE TITLE
Unable to upload big CityGML in zip

### ISSUE THREAD

**Issue by pablocbre** [AnalyticalGraphicsInc/cesium-ion-community#144] opened 2019-04-08 13:27 UTC
I am trying to upload a zip file containing a single CityGML file. The zip file weights 490Mb.

The problem is the UI seems to do nothing when I am uploading it. I've tried to both drag and drop, as well as clicking on "Add files..." and using the explorer. Neither work (the screen simply remains as it is).

I have successfully uploaded a subset of that CityGML, zipped as well, with a size of 80Mb. Everything was fine and no problem occurred.

How can I troubleshoot this?

Thanks

**Comment by pablocbre** [comment] 2019-04-08 13:52
This is where I get stuck.

![image](https://user-images.githubusercontent.com/43879499/55729394-57c7c100-5a16-11e9-8e23-ac776fdef692.png)

**Comment by hpinkos** [comment] 2019-04-08 14:24
Thanks for reporting this @pablocbre.  What browser are you using?  Do you have sample data you can share with us that would reproduce the problem?

cc @mramato

**Comment by pablocbre** [comment] 2019-04-08 14:29
Hi @hpinkos, I'm using Chrome:

![image](https://user-images.githubusercontent.com/43879499/55731852-361d0880-5a1b-11e9-984e-468693ae29a6.png)

I wouldn't mind sharing the dataset privately with you guys so you can take a look. How should I reach you out privately?

**Comment by hpinkos** [comment] 2019-04-08 14:33
Thanks @pablocbre!  I have an idea of what the problem might be, and we'll be in touch if we need the dataset to troubleshoot.  We'll give you an update when we have one =)

**Comment by pablocbre** [comment] 2019-04-08 14:36
Great, thanks @hpinkos. Let me know if there's anyway I can help.

**Comment by pablocbre** [comment] 2019-04-15 08:00
Hey @hpinkos, just wondering if you guys have advanced enough to be able to identify some workaround I could use while an actual solution comes? Thank you

**Comment by hpinkos** [comment] 2019-04-15 13:59
Sorry @pablocbre, I don't think we've had a chance to look at this yet.  My guess is it's a bug with uploading in large zip files.  Have you tried uploading the contents not zipped as a workaround?

**Comment by pablocbre** [comment] 2019-04-16 07:49
Hi @hpinkos, I am afraid the original file is to big for my account to handle it without compressing. I guess I'll have to wait for a solution with the zip. Thank you

**Comment by OmarShehata** [comment] 2019-06-27 18:11
Hey @pablocbre , we've just fixed the zip uploading issue! Can you try uploading it now and confirm that it works?

**Comment by pablocbre** [comment] 2019-06-28 07:17
Hi Omar,

Right now I have two attempts for this asset: IDs 32573 and 32784. Both of them are stuck at 66% in Tiling. What should we do?

Pablo Martín Calvo
CBRE España | Business Analytics
Paseo de la Castellana, 202. Planta 6 | 28046 Madrid
M +34 647 369 075
pablo.martin@cbre.com<mailto:pablo.martin@cbre.com> | www.cbre.es<http://www.cbre.es/>

**Comment by OmarShehata** [comment] 2019-07-16 17:09
I'm closing this since the ZIP upload issue has now been fixed. The tiling stuck at 66% is this issue https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/189#issuecomment-507174197 which we're still working on.

**Closed as completed by OmarShehata** 2019-07-16 17:09 UTC
