### ISSUE TITLE
BIM in Cesium: TypeError: pickedFeature.color is undefined

### ISSUE THREAD

**Issue by joliedegeyter** [AnalyticalGraphicsInc/cesium-ion-community#248] opened 2019-11-26 15:45 UTC
Hello everyone,
I have a BIM (revit) file (exported to IFC) that I would like to display in Cesium and being able to click on the features to show their properties. To achieve this I have already used different methods.
First I tried to transform the IFC file to Cesium3DTiles via FME, but this resulted in enormous distortions (Figure 1). Now I have converted the ifc file to .obj and .dae via IfcConvert and loaded it through Cesium ion. The geometry looks better (figure 2) but if I want to pick features I get this error: _TypeError: pickedFeature.color is undefined_
Someone who has an idea why?
You can view my cesium sandcastle via this link:  

https://sandcastle.cesium.com/index.html#c=lVZdc9o4FP0ral5iZjIyaZrutEk6mxKamCmQNqRtMszsCOsCAllyJRkCO/3ve+UPYtP0YXnA2Pfr3HvukQlDcm2YcqQDVmRJ746wOAZridNkozNDhFaEWQvOjlXhQyOtKIcpy6S7zJ1HegmKXJBD2PTmk+tYDEUvut9GxwMR2Uh9PY070dtomf741um9o+j0k18v0Sk6fVgsnx6+Pzw9ivbx8Kp7+nn05U3/ddcNR9HTY6e97m/jp8erT8lg0X0aLPric6eXPmKy/mi26Y9iTD5YTE4+yngTvf2OxeOTyPuoh02Pe9+HH1/EcNE9Hmz77eHV/cng6uM7enNyP7/dtmdqPTphpr15t3pt+j/bP2bqst8/zdzy5qb3lpme5G8Oz8ZqrMLwCsiEWUhYGjowBoQiOAGhBBjsXCjJOKDjihmyErAGg9NQsC6nSr/lz4LDOL/taOWYUGAOj8i/Y0Xw45Pio1ujV4Jj9Pt6dHEZNV2CMtJ/MiPfk2dyvoJF5mKgU6OTS89dxIPjVuH/C6+/WthWgZPaGBTQmdQTQFJTNx+BdZczrGRdWRJ7cSaD51GAmIGSYrEE4oQELEB0OmeyGkH18II0iqRGJMKJFVjKOA8KPL/1eXI1KsL/b4enf52+rnfZKgFHaqt1gjTpFEmrwO0G4I0jHZSPy3iq3RzMWlgIppmKnVdBgNPQpkVqsGKtrJZApZ6V1rOqfl7cl8eBCDYBCSRhXiY6IXOczQyshNgBGE6mwFxmwAN0QKxkTFHyvfyVe6NHhjsCZAty6v0w0Zo53482YobLhPmXElCwa2ZpQYOFvAJHHkrMZaH3JFP5+gI/KgxFEiY7WmpTM+OulFMsxgAePgLJZkQxLOGx7QPAFmYeN5O2sE8WCIOgVhxJsN9G6wKPld2EjWfgrkQdtErQYhqUzJeggqoxWvbTapCyb6WxbwqHsDM0uj37cyTG7CZREYsTKQZyozOeEzDBNcJ0KAmyYv5cIEkmLJmIRU1kBkDdpSyG7gqUu2GKS/8cF1elGR6jvv/aqiV6BbiybtdYGJJbES8JpvGTzNaw2xqOe6CVPzWq0lvhfHm8LhSKVXGSaovKA1ok88uRYjbgn3aNNpWKxh0GCorf5vFaVfsdhpfI7gJIRibopsh1tzvYIZrACovicHAca23wl99VBLjS2sx9C/UVwIXFe1OIsiCcBK/2KG/AbbVqdO8tzVndgs7qmbgG8AK2x1Khto55lIXg8m3FH15vvDlrJvc2mFSpn/t9QZf5bjC3S7Xy58uC+xRVPFThOKoa0VyrJbp5+RepvLqchhms8ItX0S9psVzIqmZJBkg8QnwPPtFW8/wg2QKRDKVdyts7GA0pwliWbUGh6bqeJcO9zxUNtYHQZx6ba/bq4uI3kTW02yCTNNj8s0wvGkVe0nND8LjsjYDifKiFvWB9OYZyZvBID9r0zVH9RVaEBK1W7dA4qox3e2fBaJMC7Q/v77r/9IffusWL4+Do4Ny6jYQPRYa/RZJq4/x7MKAU/4MkqSfLhpMMUTkaW+sDz8Mq6JyLFRH8Ynyw959jfEBiiX/o0DLNpLwTWxgffDgP0b8RJjXjeKgNcU0l26BLAeR8fvzhc2GilJ6HeOvL7kc7reWEmVrm/wA

thanks!

![figure1](https://user-images.githubusercontent.com/44199515/69647604-1437cb00-106a-11ea-8318-adca35f0ceb1.png)
(figure 1)

![figure2](https://user-images.githubusercontent.com/44199515/69648452-a68c9e80-106b-11ea-8360-55e219cc9202.png)
(figure 2)

**Comment by OmarShehata** [comment] 2019-12-10 22:06
The 3D Tiles format does allow for exactly this type of use case, but the Cesium ion tiling pipeline doesn't current support reading feature/metadata from BIM/CAD models. We have an open feature request for this here:

https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/132

Currently the only formats we support reading feature metadata for is CityGML and KML/COLLADA. There's some more details as well as sample code on how to access those features in CesiumJS here: https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/201

I'm closing this as a duplicate of the linked issue but feel free to follow up here or the above issues if you have any more questions.

**Closed as completed by OmarShehata** 2019-12-10 22:06 UTC
